name: Memory Utilization Workflow

on: [push, pull_request]

jobs:
  show-memory-utilization:
    runs-on: [self-hosted, Linux, x64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set execute permissions for entrypoint.sh
        run: chmod +x entrypoint.sh

      - name: Run Memory Utilization
        uses: ./
        with:
          script-path: ./entrypoint.sh
