name: Memory Utilization Workflow

on: [push, pull_request]

jobs:
  show-memory-utilization:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show Memory Utilization
        id: memory-utilization
        run: ./entrypoint.sh

      - name: Display Memory Utilization
        run: echo "Memory Utilization:${{ steps.memory-utilization.outputs.memory }}"
